Answer.create name: "1"
Answer.create name: "2"
Answer.create name: "3"
Answer.create name: "4"
Answer.create name: "5"
Answer.create name: "6"
Answer.create name: "7"
Answer.create name: "Si"
Answer.create name: "No"
Answer.create name: "Queda poca"
Answer.create name: "Suficiente"
Answer.create name: "Poca"
Answer.create name: "No hubo"
Answer.create name: "Otros", with_value: true

Answer.create name: "Bolsas de basura"
Answer.create name: "Cloro"
Answer.create name: "Paños"
Answer.create name: "Tachos"
Answer.create name: "Escobillas"
Answer.create name: "Recogedores"
Answer.create name: "Detergente"
Answer.create name: "Escoba"
Answer.create name: "Bateas"
Answer.create name: "Trapeador"
Answer.create name: "Desinfectante"
Answer.create name: "Linternas"
Answer.create name: "Lamparines"
Answer.create name: "Velas"
Answer.create name: "Generador eléctrico"
Answer.create name: "Papel higiénico"
Answer.create name: "Pañales niños"
Answer.create name: "Pañales ancianos"
Answer.create name: "Repelente"
Answer.create name: "Toallas higiénicas"
Answer.create name: "Jabón"
Answer.create name: "Shampoo"
Answer.create name: "Cepillo de dientes"
Answer.create name: "Pasta dental"

Answer.create name: "Mujer embarazada"
Answer.create name: "Niño menor a 3 años"
Answer.create name: "Niño menor a 12 años"
Answer.create name: "Adulto mayor"

Answer.create name: "Para las heridas"
Answer.create name: "Para la diarrea"
Answer.create name: "Para la fiebre"
Answer.create name: "Para la tos y resfrío"
Answer.create name: "Para la infección (antibióticos)"
Answer.create name: "Vacunas"

Answer.create name: "Municipalidad"
Answer.create name: "No hay nadie encargado del recojo de basura"

Answer.create name: "Robos"
Answer.create name: "Agresiones verbales"
Answer.create name: "Agresiones físicas"
Answer.create name: "Tocamientos indebidos"
Answer.create name: "Violaciones"
Answer.create name: "No se han reportado incidencias"

Answer.create name: "No se resolvió"
Answer.create name: "Se expulsó al agresor"
Answer.create name: "La policía intervino"

Answer.create name: "Malversación de donaciones/recursos"
Answer.create name: "Velas dentro de carpas"
Answer.create name: "Venta y/o consumo de drogas"
Answer.create name: "Pandillaje"
Answer.create name: "Prostitución"
Answer.create name: "Ataques de animales"
Answer.create name: "No se han detectado"
