Answer.create name: "1"
Answer.create name: "2"
Answer.create name: "3"
Answer.create name: "4"
Answer.create name: "5"
Answer.create name: "6"
Answer.create name: "7"
Answer.create name: "Si"
Answer.create name: "No"
Answer.create name: "Hay escasez"
Answer.create name: "Otros", with_value: true

Answer.create name: "Bolsas de basura"
Answer.create name: "Cloro"
Answer.create name: "Paños"
Answer.create name: "Tachos"
Answer.create name: "Escobillas"
Answer.create name: "Recogedores"
Answer.create name: "Detergente"
Answer.create name: "Escoba"
Answer.create name: "Bateas"
Answer.create name: "Trapeador"
Answer.create name: "Desinfectante"
Answer.create name: "Velas"
Answer.create name: "Lamparines"
Answer.create name: "Generador eléctrico"
Answer.create name: "Gasolina para generador eléctrico"
